# Generated by Django 3.1.3 on 2023-08-18 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0017_weightentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 18)),
        ),
    ]
