# Generated by Django 3.1.3 on 2023-08-22 02:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0021_auto_20230818_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='training',
        ),
        migrations.RemoveField(
            model_name='training',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='training',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='training',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='training',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='exercises',
        ),
        migrations.AddField(
            model_name='training',
            name='ended',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 2, 29, 2, 536249, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(to='trainings.Exercise'),
        ),
        migrations.AddField(
            model_name='training',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 2, 29, 2, 536249, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='trainings',
            field=models.ManyToManyField(to='trainings.Training'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='series',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_per',
            field=models.CharField(choices=[('total', 'Total'), ('per hand', 'Per Hand')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 2, 29, 2, 537249, tzinfo=utc)),
        ),
    ]
