# Generated by Django 3.1.3 on 2023-08-22 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0022_auto_20230822_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trainings.training'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.TextField(default='Exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='series',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_kg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_per',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='ended',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 10, 24, 27, 939798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 10, 24, 27, 939798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 10, 24, 27, 941814, tzinfo=utc)),
        ),
    ]
