# Generated by Django 3.1.3 on 2023-08-22 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0023_auto_20230822_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='ended',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 10, 29, 12, 959689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 10, 29, 12, 959689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 10, 29, 12, 960689, tzinfo=utc)),
        ),
    ]
