# Generated by Django 3.1.3 on 2023-08-22 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0024_auto_20230822_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight_per',
            field=models.TextField(blank=True, default='total', null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='ended',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 10, 35, 15, 994601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 10, 35, 15, 994601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 10, 35, 15, 995601, tzinfo=utc)),
        ),
    ]
