# Generated by Django 3.1.3 on 2023-08-22 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0025_auto_20230822_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='ended',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 11, 53, 42, 861613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 11, 53, 42, 861613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 11, 53, 42, 862609, tzinfo=utc)),
        ),
    ]
