# Generated by Django 3.1.3 on 2023-08-25 07:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0026_auto_20230822_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='ended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='training',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='training',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 25, 7, 57, 0, 697218, tzinfo=utc)),
        ),
    ]
