# Generated by Django 3.1.3 on 2023-08-25 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0027_auto_20230825_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 25, 9, 47, 38, 296879, tzinfo=utc)),
        ),
    ]
