# Generated by Django 3.1.3 on 2023-08-25 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0028_auto_20230825_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 25, 15, 38, 47, 325892, tzinfo=utc)),
        ),
    ]
